server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /squadxml/ {
        proxy_pass https://squadxml.tacticalteam.de;
        proxy_set_header Host squadxml.tacticalteam.de;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
        proxy_ssl_name squadxml.tacticalteam.de;
    }

    location /squadxml_tvt/ {
        proxy_pass https://squadxml.tacticalteam.de;
        proxy_set_header Host squadxml.tacticalteam.de;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
        proxy_ssl_name squadxml.tacticalteam.de;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}